//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCValidator.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGCValidator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a App di Verifica del Certificato Vaccinale e registrazione dell&apos;accesso operatori. Nessun dato sensibile viene conservato..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Birth date: .
        /// </summary>
        public static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Identifier: .
        /// </summary>
        public static string CertificateIdentifierLabel {
            get {
                return ResourceManager.GetString("CertificateIdentifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Country: .
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disease: .
        /// </summary>
        public static string DiseaseLabel {
            get {
                return ResourceManager.GetString("DiseaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dose .
        /// </summary>
        public static string DoseText {
            get {
                return ResourceManager.GetString("DoseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error while reading.
        /// </summary>
        public static string ErrorReadingText {
            get {
                return ResourceManager.GetString("ErrorReadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expire: .
        /// </summary>
        public static string ExpireDateLabel {
            get {
                return ResourceManager.GetString("ExpireDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PROSOFT DCC Validator.
        /// </summary>
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Validate certificate.
        /// </summary>
        public static string InformationHeader {
            get {
                return ResourceManager.GetString("InformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sistema di validazione e accesso alla struttura PROSOFT..
        /// </summary>
        public static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Emesso:.
        /// </summary>
        public static string IssuedDateLabel {
            get {
                return ResourceManager.GetString("IssuedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ente emittente:.
        /// </summary>
        public static string IssuerLabel {
            get {
                return ResourceManager.GetString("IssuerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna Informazione.
        /// </summary>
        public static string MissingDataText {
            get {
                return ResourceManager.GetString("MissingDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Produzione.
        /// </summary>
        public static string ProductionText {
            get {
                return ResourceManager.GetString("ProductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recovered.
        /// </summary>
        public static string RecoveredText {
            get {
                return ResourceManager.GetString("RecoveredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recovered.
        /// </summary>
        public static string RecoveryHeader {
            get {
                return ResourceManager.GetString("RecoveryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Positive date: .
        /// </summary>
        public static string RecTestDateLabel {
            get {
                return ResourceManager.GetString("RecTestDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Refresh trust list.
        /// </summary>
        public static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ScanBottomText {
            get {
                return ResourceManager.GetString("ScanBottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scan.
        /// </summary>
        public static string ScanButtonText {
            get {
                return ResourceManager.GetString("ScanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string ScanCancelText {
            get {
                return ResourceManager.GetString("ScanCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Flash.
        /// </summary>
        public static string ScanFlashText {
            get {
                return ResourceManager.GetString("ScanFlashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scan certificate.
        /// </summary>
        public static string ScanTopText {
            get {
                return ResourceManager.GetString("ScanTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test date: .
        /// </summary>
        public static string TestDateLabel {
            get {
                return ResourceManager.GetString("TestDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tested.
        /// </summary>
        public static string TestedText {
            get {
                return ResourceManager.GetString("TestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tested.
        /// </summary>
        public static string TestHeader {
            get {
                return ResourceManager.GetString("TestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test centre: .
        /// </summary>
        public static string TestingCentreLabel {
            get {
                return ResourceManager.GetString("TestingCentreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test manifacturer: .
        /// </summary>
        public static string TestManifacturerLabel {
            get {
                return ResourceManager.GetString("TestManifacturerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test name: .
        /// </summary>
        public static string TestNameLabel {
            get {
                return ResourceManager.GetString("TestNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Result date: .
        /// </summary>
        public static string TestResultDateLabel {
            get {
                return ResourceManager.GetString("TestResultDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test result: .
        /// </summary>
        public static string TestResultLabel {
            get {
                return ResourceManager.GetString("TestResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sample origin: .
        /// </summary>
        public static string TestSampleOriginLabel {
            get {
                return ResourceManager.GetString("TestSampleOriginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test type: .
        /// </summary>
        public static string TestTypeLabel {
            get {
                return ResourceManager.GetString("TestTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transliterated name: .
        /// </summary>
        public static string TranNameLabel {
            get {
                return ResourceManager.GetString("TranNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VACCINATO.
        /// </summary>
        public static string VaccinatedText {
            get {
                return ResourceManager.GetString("VaccinatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data:.
        /// </summary>
        public static string VaccinationDateLabel {
            get {
                return ResourceManager.GetString("VaccinationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vaccinazione.
        /// </summary>
        public static string VaccinationHeader {
            get {
                return ResourceManager.GetString("VaccinationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Responsabile:.
        /// </summary>
        public static string VaccinationProviderLabel {
            get {
                return ResourceManager.GetString("VaccinationProviderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Auth holder: .
        /// </summary>
        public static string VaccineAuthLabel {
            get {
                return ResourceManager.GetString("VaccineAuthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descrizione:.
        /// </summary>
        public static string VaccineDescriptionLabel {
            get {
                return ResourceManager.GetString("VaccineDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lotto:.
        /// </summary>
        public static string VaccineLotLabel {
            get {
                return ResourceManager.GetString("VaccineLotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome:.
        /// </summary>
        public static string VaccineNameLabel {
            get {
                return ResourceManager.GetString("VaccineNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valido da:.
        /// </summary>
        public static string ValidFromLabel {
            get {
                return ResourceManager.GetString("ValidFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valido fino a:.
        /// </summary>
        public static string ValidUntilLabel {
            get {
                return ResourceManager.GetString("ValidUntilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verifica.
        /// </summary>
        public static string VerificationText {
            get {
                return ResourceManager.GetString("VerificationText", resourceCulture);
            }
        }
    }
}
